In [20]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import statistics

In [21]:
df=pd.read_csv('gym_members_exercise_tracking_synthetic_data.csv')
print("Number of missing values per column:")
display(df.isnull().sum())

Number of missing values per column:

Age                              10
Gender                           71
Weight (kg)                      22
Height (m)                       26
Max_BPM                          21
Avg_BPM                          30
Resting_BPM                      19
Session_Duration (hours)         23
Calories_Burned                  23
Workout_Type                     61
Fat_Percentage                   16
Water_Intake (liters)            24
Workout_Frequency (days/week)    58
Experience_Level                 57
BMI                              30
dtype: int64

In [22]:
df_cleaned=df.dropna()
display(df_cleaned)

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
0,34.0,Female,86.7,1.86,174,152.0,74.0,1.12,712.0,Strength,12.8,2.4,5.0,2.0,14.31
1,26.0,Female,84.7,1.83,166,156.0,73.0,1.00,833.0,Strength,27.9,2.8,5.0,2.0,33.49
2,22.0,Male,64.8,1.85,187,166.0,64.0,1.24,1678.0,Cardio,28.7,1.9,3.0,2.0,12.73
3,54.0,Female,75.3,1.82,187,169.0,58.0,1.45,628.0,Cardio,31.8,2.4,4.0,1.0,20.37
4,34.0,Female,52.8,1.74,177,169.0,66.0,1.60,1286.0,Strength,26.4,3.2,4.0,2.0,20.83
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1795,54.0,Male,88.5,2.00,173,134.0,58.0,1.11,1388.0,HIIT,27.7,3.7,3.0,2.0,36.73
1796,52.0,Male,84.3,1.69,164,169.0,54.0,0.77,1367.0,HIIT,32.6,2.9,3.0,2.0,15.11
1797,47.0,Male,70.1,1.84,188,129.0,67.0,1.20,1261.0,Strength,28.4,2.5,3.0,2.0,17.99
1798,35.0,Male,49.3,1.71,180,152.0,73.0,1.04,956.0,Cardio,32.9,1.7,4.0,3.0,12.65
1799,40.0,Male,79.5,1.92,184,156.0,52.0,1.29,1178.0,Strength,14.7,1.5,4.0,1.0,23.51

In [23]:
display(df_cleaned.isnull().sum())
df_cleaned.info()

Age                              0
Gender                           0
Weight (kg)                      0
Height (m)                       0
Max_BPM                          0
Avg_BPM                          0
Resting_BPM                      0
Session_Duration (hours)         0
Calories_Burned                  0
Workout_Type                     0
Fat_Percentage                   0
Water_Intake (liters)            0
Workout_Frequency (days/week)    0
Experience_Level                 0
BMI                              0
dtype: int64

<class 'pandas.core.frame.DataFrame'>
Index: 1359 entries, 0 to 1799
Data columns (total 15 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            1359 non-null   float64
 1   Gender                         1359 non-null   object
 2   Weight (kg)                    1359 non-null   float64
 3   Height (m)                     1359 non-null   float64
 4   Max_BPM                        1359 non-null   object
 5   Avg_BPM                        1359 non-null   float64
 6   Resting_BPM                    1359 non-null   float64
 7   Session_Duration (hours)       1359 non-null   float64
 8   Calories_Burned                1359 non-null   float64
 9   Workout_Type                   1359 non-null   object
 10  Fat_Percentage                 1359 non-null   float64
 11  Water_Intake (liters)          1359 non-null   float64
 12  Workout_Frequency (days/week)  1359 non-null   float64
 13  Experience_Level               1359 non-null   float64
 14  BMI                            1359 non-null   float64
dtypes: float64(12), object(3)
memory usage: 169.9+ KB

In [24]:
display(df_cleaned.mean(numeric_only=True))

Age                                34.510670
Weight (kg)                        67.539809
Height (m)                          1.738668
Avg_BPM                           146.097866
Resting_BPM                        63.863870
Session_Duration (hours)            1.389338
Calories_Burned                  1034.690949
Fat_Percentage                     23.432230
Water_Intake (liters)               2.732671
Workout_Frequency (days/week)       3.351729
Experience_Level                    1.827815
BMI                                20.078057
dtype: float64

In [25]:
display(df_cleaned.mode())

,Age,Gender,Weight (kg),Height (m),Max_BPM,Avg_BPM,Resting_BPM,Session_Duration (hours),Calories_Burned,Workout_Type,Fat_Percentage,Water_Intake (liters),Workout_Frequency (days/week),Experience_Level,BMI
0,18.0,Female,40.0,2.0,192,169.0,74.0,2.0,1783.0,Strength,10.0,3.4,3.0,2.0,12.32

In [26]:
display(df_cleaned.median(numeric_only=True))

Age                                33.00
Weight (kg)                        65.10
Height (m)                          1.73
Avg_BPM                           145.00
Resting_BPM                        65.00
Session_Duration (hours)            1.37
Calories_Burned                  1032.00
Fat_Percentage                     24.10
Water_Intake (liters)               2.80
Workout_Frequency (days/week)       3.00
Experience_Level                    2.00
BMI                                18.71
dtype: float64

In [27]:
display(df_cleaned.var(numeric_only=True))

Age                                 150.831808
Weight (kg)                         392.563473
Height (m)                            0.015339
Avg_BPM                             235.614127
Resting_BPM                          62.457891
Session_Duration (hours)              0.138214
Calories_Burned                  104743.814579
Fat_Percentage                       34.801332
Water_Intake (liters)                 0.500773
Workout_Frequency (days/week)         0.914487
Experience_Level                      0.552068
BMI                                  44.842665
dtype: float64

In [28]:
display(df_cleaned.std(numeric_only=True))

Age                               12.281360
Weight (kg)                       19.813215
Height (m)                         0.123852
Avg_BPM                           15.349727
Resting_BPM                        7.903030
Session_Duration (hours)           0.371772
Calories_Burned                  323.641491
Fat_Percentage                     5.899265
Water_Intake (liters)              0.707653
Workout_Frequency (days/week)      0.956288
Experience_Level                   0.743013
BMI                                6.696467
dtype: float64

In [29]:
display(df_cleaned.select_dtypes(include='number').apply(lambda col: (col - col.mean()).abs().mean()))

Age                               10.640023
Weight (kg)                       16.091891
Height (m)                         0.099488
Avg_BPM                           13.459170
Resting_BPM                        7.083369
Session_Duration (hours)           0.299310
Calories_Burned                  260.841675
Fat_Percentage                     4.653013
Water_Intake (liters)              0.621741
Workout_Frequency (days/week)      0.827297
Experience_Level                   0.623754
BMI                                5.275765
dtype: float64